# Generated by Django 4.2.7 on 2025-10-18 22:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('audio_file', models.FileField(upload_to='audio_recordings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'webm', 'm4a'])], verbose_name='Arquivo de Áudio')),
                ('duration', models.FloatField(blank=True, help_text='Duração em segundos', null=True, verbose_name='Duração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gravação de Áudio',
                'verbose_name_plural': 'Gravações de Áudio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(choices=[('alegria', 'Alegria'), ('tristeza', 'Tristeza'), ('raiva', 'Raiva'), ('medo', 'Medo'), ('surpresa', 'Surpresa'), ('nojo', 'Nojo'), ('neutro', 'Neutro')], max_length=20, verbose_name='Emoção Dominante')),
                ('confidence', models.FloatField(help_text='Confiança da análise (0-1)', verbose_name='Confiança')),
                ('emotions_data', models.JSONField(help_text='Dados detalhados de todas as emoções detectadas', verbose_name='Dados das Emoções')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Analisado em')),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_analysis', to='emotion_analysis.audiorecording', verbose_name='Gravação')),
            ],
            options={
                'verbose_name': 'Análise de Emoção',
                'verbose_name_plural': 'Análises de Emoções',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
