# Generated by Django 4.2.7 on 2026-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_analysis', '0002_consultation_userprofile_message_gamescore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score', '-created_at'], 'verbose_name': 'Pontuação do Jogo', 'verbose_name_plural': 'Pontuações dos Jogos'},
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='level',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='time_played',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='game_name',
            field=models.CharField(default='Game', max_length=100),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='time_spent',
            field=models.IntegerField(default=0, help_text='Tempo em segundos'),
        ),
    ]
